import type { Metadata } from "next";

import { DM_Sans } from "next/font/google";
import ChatWindow from "./ui/ChatWindow";
import "./globals.css";

const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "700"], // Add weights as needed
  variable: "--font-dm-sans",   // Optional: use as CSS variable
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={dmSans.className}>
      <body
        className={` antialiased`}
      >
        {children}
        
        <ChatWindow />
      </body>
    </html>
  );
}
